### ISSUE TITLE
Windows computers can't build with button

### ISSUE THREAD

**Issue by mucolon** [PhonicCanine/vscode-microbit#6] opened 2020-09-21 05:43 UTC
When you use the build button, I know this command is run `uflash "path/to/directory/file.py"`

This works fine with Mac computers, however Windows computers require `python3 -m` as a prefix. This prefix doesn't affect Macs, Macs work with both commands.

I suggest editing `extension.js` line 35 from

`var text = "uflash \"" + vscode.window.activeTextEditor.document.fileName + "\"";`

to

`var text = "python3 -m uflash \"" + vscode.window.activeTextEditor.document.fileName + "\"";`

Lmk what you think @PhonicCanine

**Comment by MrMazzone** [comment] 2021-02-27 19:37
I can confirm.  This fix is needed to work on Windows.

**Comment by PhonicCanine** [comment] 2021-03-07 16:47
This should be fixed now (version 0.3.0) -- it'll try `uflash` & `python3 -m uflash`, and then use whichever works.
This behavior is because on some Windows installations (notably, with the Windows Store version of Python3), it can be possible for `uflash` to work, but `python3 -m uflash` not to work.
I'll close the issue for now, but please feel free to let me know if anything doesn't work, I've got some time to spend on this for a while.

**Comment by MrMazzone** [comment] 2021-03-07 17:05
@PhonicCanine My issue is on Windows python3 tends to not be a recognized command.  See here: https://stackoverflow.com/questions/34212036/python-3-installation-on-windows-running-from-command-line/34223417#34223417

So on my machine, I can type `python -m uflash "coolcode.py"` and it will flash to my Micro:bit, but the "Build current file to Micro:bit" button just does nothing.

**Comment by PhonicCanine** [comment] 2021-03-07 17:08
Okay I'll add `python -m uflash` as an alternative fallback in the next few days, thanks for letting me know.

**Comment by PhonicCanine** [comment] 2021-03-08 00:29
Should be fixed now with 0.3.1, it'll first try `uflash` then `python3 -m uflash` and finally `python -m uflash`.

**Closed as completed by PhonicCanine** 2021-03-08 00:29 UTC

**Comment by MrMazzone** [comment] 2021-03-08 00:43
Confirmed.  Works perfectly!  Thank you.
